# This is a basic workflow to help you get started with Actions

name: Build and deploy package to nuget

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
        with:
          dotnet-version: '5.0.x'
      - name: build with dotnet
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test
      - name: Create the Package
        run: dotnet pack --configuration Release
      - name: Publish
        run: dotnet nuget push "./ErinaScraper/bin/Release/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} -p:PackageVersion=1.0.2  --source https://api.nuget.org/v3/index.json
